[target.'cfg(all())']
rustflags = [
  "-Dfuture-incompatible",
  "-Dnonstandard-style",
  "-Wunused",
  "-Dmissing_crate_level_docs",
  "-Dmissing_docs",
  "-Dclippy::all",
  "-Dclippy::pedantic",
  "-Dclippy::nursery",
  "-Dclippy::as_conversions",
  # "-Dclippy::cargo",
  "-Aclippy::module-name-repetitions",
  "-Aclippy::needless-pass-by-value",
  "-Aclippy::use-self",
  "-Aclippy::implicit-return",
  "-Aclippy::missing_docs_in_private_items",
  "-Aclippy::shadow_reuse",
  "-Aclippy::shadow_unrelated",
  "-Aclippy::pub-use",
  "-Aclippy::exhaustive_structs",
  "-Aclippy::exhaustive_enums",
]

# https://gist.github.com/Mefistophell/9787e1b6d2d9441c16d2ac79d6a505e6
# [target.x86_64-pc-windows-gnu]
# linker = "x86_64-w64-mingw32-gcc"